### ISSUE TITLE
expand snippet with "/"

### ISSUE THREAD

**Issue by JJK96** [andreyorst/kakoune-snippet-collection#3]
Because the filename is used to contain the expansion string, it cannot contain `/`.

**Comment by andreyorst** [comment]
https://github.com/occivink/kakoune-snippets#snippets-directorykak

**Comment by JJK96** [comment]
Ah, thx

**Comment by andreyorst** [comment]
Perhaps we can raise an issue to support this via something like `<slash>` if it is necessary
